"""empty message

Revision ID: 1d46944139e7
Revises: 24634388f670
Create Date: 2023-06-17 17:59:43.803082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d46944139e7'
down_revision = '24634388f670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=False),
    sa.Column('occupantName', sa.String(), nullable=True),
    sa.Column('bookingReference', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('roomName', sa.String(), nullable=True),
    sa.Column('roomBlock', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('prestoTransactionId', sa.String(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('korbaId', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
