"""empty message

Revision ID: 24634388f670
Revises: f6ea7b3f2531
Create Date: 2023-06-17 16:11:48.787622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24634388f670'
down_revision = 'f6ea7b3f2531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
