"""empty message

Revision ID: 29574dba7e99
Revises: d4eabbd03e84
Create Date: 2023-06-17 12:52:38.969601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29574dba7e99'
down_revision = 'd4eabbd03e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('bedsTaken', sa.Integer(), nullable=True),
    sa.Column('bedsAvailable', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('maxOccupancy', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('vacant', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('room_config')
    # ### end Alembic commands ###
