"""empty message

Revision ID: 70dc027e5f7a
Revises: d1a8098dbd01
Create Date: 2023-06-28 11:29:19.818284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dc027e5f7a'
down_revision = 'd1a8098dbd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
