"""empty message

Revision ID: b796afa8e50c
Revises: 70dc027e5f7a
Create Date: 2023-06-28 11:35:26.858522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b796afa8e50c'
down_revision = '70dc027e5f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxOccupancy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('maxOccupancy')

    # ### end Alembic commands ###
