"""empty message

Revision ID: cb04af1786d1
Revises: cce4f3cc52d2
Create Date: 2023-06-28 11:13:21.963527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb04af1786d1'
down_revision = 'cce4f3cc52d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=True),
    sa.Column('transactionId', sa.Integer(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('prestoId', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('transactionType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=False),
    sa.Column('occupantName', sa.String(), nullable=True),
    sa.Column('bookingReference', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('roomName', sa.String(), nullable=True),
    sa.Column('roomBlock', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('prestoTransactionId', sa.String(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('korbaId', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('balance')

    op.drop_table('transactions')
    op.drop_table('ledger')
    # ### end Alembic commands ###
