"""empty message

Revision ID: cce4f3cc52d2
Revises: 1d46944139e7
Create Date: 2023-06-17 18:49:15.028338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce4f3cc52d2'
down_revision = '1d46944139e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=True),
    sa.Column('transactionId', sa.Integer(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('prestoId', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('transactionType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('balance')

    op.drop_table('ledger')
    # ### end Alembic commands ###
