"""empty message

Revision ID: d8b8489bf808
Revises: b796afa8e50c
Create Date: 2023-06-28 11:57:09.884371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b8489bf808'
down_revision = 'b796afa8e50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=True),
    sa.Column('due', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=True),
    sa.Column('transactionId', sa.Integer(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('prestoId', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('transactionType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('maxOccupancy', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('roomnumber', sa.String(), nullable=True),
    sa.Column('roomid', sa.String(), nullable=True),
    sa.Column('roomCost', sa.Float(), nullable=True),
    sa.Column('amountPaid', sa.Float(), nullable=True),
    sa.Column('due', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('maxOccupancy', sa.Integer(), nullable=True),
    sa.Column('occupancyStatus', sa.String(), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=True),
    sa.Column('bedsAvailable', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('roomtype', sa.String(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('space', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('bedsTaken', sa.Integer(), nullable=True),
    sa.Column('bedsAvailable', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('maxOccupancy', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('vacant', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('basic', sa.Float(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('space', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupantId', sa.String(), nullable=False),
    sa.Column('occupantName', sa.String(), nullable=True),
    sa.Column('bookingReference', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('roomName', sa.String(), nullable=True),
    sa.Column('roomBlock', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('prestoTransactionId', sa.String(), nullable=True),
    sa.Column('momoId', sa.String(), nullable=True),
    sa.Column('korbaId', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('room_type')
    op.drop_table('room_location')
    op.drop_table('room_config')
    op.drop_table('room')
    op.drop_table('occupant')
    op.drop_table('ledger')
    op.drop_table('courses')
    op.drop_table('blocks')
    # ### end Alembic commands ###
